POST http://localhost:8080/events
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRoaXJkX3Rlc3RAZXhhcGxlLmNvbSIsImV4cCI6MTcxODA4MTE4OSwidXNlcklkIjoxfQ.GDReYG-vTbSGDiLQtBEEg_pDPByeQqpZSWxVqw5PX6Y

{
    "name": "event name",
    "description": "event description",
    "location": "event location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}