POST http://localhost:8080/events
content-type: application/json

{
    "name": "event name",
    "description": "event description",
    "location": "event location",
    "dateTime": "2024-12-02-01T16:30:00.000Z"
}