POST http://localhost:8080/events
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlY29uZF90ZXN0QGV4YXBsZS5jb20iLCJleHAiOjE3MTc5MDI0NjcsInVzZXJJZCI6Mn0.gGKpOdBd3_gnwBS2503jKJIQKVadVNlWPlv2ryH0gDc

{
    "name": "event name",
    "description": "event description",
    "location": "event location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}